---

# ------------------------------------------------------------------------------
# File        : ctlabs-ansible/roles/ctlabs_xrdp/defaults/main.yml
# Description : main defaults
# ------------------------------------------------------------------------------

versions:

ctlabs_xrdp:
  defaults:
    pkgs:
      debian:
        - name: xserver-xorg-core
          install_recommends: false
        - name: xserver-xorg-video-qxl
        - name: xinit
        - name: x11-utils
        - name: xrdp
        - name: xorgxrdp
        - name: xfce4
        - name: xfce4-terminal
        - name: xfce4-screenshooter
        - name: desktop-base
        - name: chromium
        - name: flameshot
        - name: git
        - name: jq
        - name: tmux
        - name: htop
        - name: python3-pip
        - name: python3-pytest
        - name: python3-requests
        - name: sublime-text
        - name: terraform
        - name: google-cloud-cli
      redhat: []
    repos:
      dracula:
        name : Dracula.theme
        url  : https://github.com/dracula/xfce4-terminal.git
        tmp  : /tmp/dracula
        dir  : /usr/share/xfce4/terminal/colorschemes/
      debian:
        - name: hashicorp
          type: main
          url : https://apt.releases.hashicorp.com 
          key : https://apt.releases.hashicorp.com/gpg
        - name: gcp-sdk
          type: main
          url : https://packages.cloud.google.com/apt
          key : https://packages.cloud.google.com/apt/doc/apt-key.gpg
        - name: sublimehq
          type: main
          url : https://download.sublimetext.com/
          key : https://download.sublimetext.com/sublimehq-pub.gpg
      redhat: []
    config:
      apt_keys : /etc/apt/keyrings
      startwm:
        template: startwm.sh.j2
        file    : /etc/xrdp/startwm.sh
      tmux:
        template: tmux.conf.j2
        file    : /etc/tmux.conf
      skeleton:
        - template: terminalrc.j2
          file    : terminalrc
          dir     : /etc/skel/.config/xfce4/terminal
        - template: xsettings.xml.j2
          file    : xsettings.xml
          dir     : /etc/skel/.config/xfce4/xfconf/xfce-perchannel-xml
    service:
      name : xrdp.service
    login:
      user   : ctlabs
      pass   : "$6$XkUy88ozFYT1Ezr8$.ZPa/PWOOswMcvZmIZITGO6VtcKepkqegKJJitSSyFdycve0UbHPJHPBGDN/HCUd.DBGzzd2xwlUjzsm0dQO./"
      group  : ctlabs
      groups : [sudo]
  os:
    - debian12
  virtype:
    - kvm
