---

# ------------------------------------------------------------------------------
# File        : ctlabs-ansible/roles/ctlabs_xrdp/defaults/main.yml
# Description : main defaults
# ------------------------------------------------------------------------------

versions:

ctlabs_xrdp:
  defaults:
    pkgs:
      debian:
        - name: xserver-xorg-core
          install_recommends: false
        - name: xserver-xorg-video-qxl
        - name: xinit
        - name: x11-utils
        - name: xrdp
        - name: xorgxrdp
        - name: xfce4
        - name: xfce4-terminal
        - name: desktop-base
        - name: chromium
        - name: git
      redhat: []
    repos:
      dracula:
        name : Dracula.theme
        url  : https://github.com/dracula/xfce4-terminal.git
        tmp  : /tmp/dracula
        dir  : /usr/share/xfce4/terminal/colorschemes/
    config:
      startwm:
        template: startwm.sh.j2
        file    : /etc/xrdp/startwm.sh
    service:
      name : xrdp.service
  os:
    - debian12
  virtype:
    - kvm
